// Builds the shipped images from assets/source/ (run: npm run assets).
// Writes assets/images/atlas-*.webp, assets/images/*-bg.webp and js/atlas-data.js.
import sharp from 'sharp';
import fs from 'node:fs';
import path from 'node:path';
import {ATLASES, BACKGROUNDS, RENDER_SCALE} from './sprites.mjs';

const SRC = 'assets/source', OUT = 'assets/images', PAD = 2, MAX_ROW = 2048;
const files = {}, sprites = {}, backgrounds = {};

async function extract({src, crop, maxW}) {
  let img = sharp(path.join(SRC, src));
  const meta = await img.metadata();
  const [x, y, w, h] = crop || [0, 0, meta.width, meta.height];
  img = img.extract({left: x, top: y, width: w, height: h});
  const width = maxW ? Math.min(w, Math.round(maxW * RENDER_SCALE)) : w;
  const height = Math.max(1, Math.round(h * width / w));
  if (width !== w) img = img.resize(width, height, {kernel: 'lanczos3'});
  return {buffer: await img.ensureAlpha().png().toBuffer(), width, height};
}

// Shelf packing: tallest sprites first, rows up to MAX_ROW wide.
function pack(items) {
  items.sort((a, b) => b.height - a.height);
  let x = PAD, y = PAD, rowH = 0, width = 0;
  for (const it of items) {
    if (x + it.width + PAD > MAX_ROW) { x = PAD; y += rowH + PAD; rowH = 0; }
    it.x = x; it.y = y;
    x += it.width + PAD; rowH = Math.max(rowH, it.height); width = Math.max(width, x);
  }
  return {width, height: y + rowH + PAD};
}

for (const [group, defs] of Object.entries(ATLASES)) {
  const items = [];
  for (const [name, def] of Object.entries(defs)) items.push({name, ...(await extract(def))});
  const size = pack(items);
  const file = `atlas-${group}.webp`;
  await sharp({create: {width: size.width, height: size.height, channels: 4, background: {r: 0, g: 0, b: 0, alpha: 0}}})
    .composite(items.map(it => ({input: it.buffer, left: it.x, top: it.y})))
    .webp({quality: 90, alphaQuality: 100, effort: 6})
    .toFile(path.join(OUT, file));
  files[file] = [size.width, size.height];
  for (const it of items) sprites[it.name] = [file, it.x, it.y, it.width, it.height];
}

for (const [name, def] of Object.entries(BACKGROUNDS)) {
  const {buffer, width, height} = await extract(def);
  const file = `${name}.webp`;
  await sharp(buffer).removeAlpha().webp({quality: 82, effort: 6}).toFile(path.join(OUT, file));
  files[file] = [width, height];
  backgrounds[name] = file;
}

const json = o => '{\n' + Object.entries(o).map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`).join('\n') + '\n}';
fs.writeFileSync('js/atlas-data.js',
  '// Generated by tools/build-assets.mjs from tools/sprites.mjs. Do not edit by hand.\n' +
  `export const FILES = ${json(files)};\n` +
  `// name: [file, x, y, w, h]\n` +
  `export const SPRITES = ${json(sprites)};\n` +
  `export const BACKGROUNDS = ${json(backgrounds)};\n`);

let total = 0;
for (const f of Object.keys(files)) {
  const kb = fs.statSync(path.join(OUT, f)).size / 1024; total += kb;
  console.log(f.padEnd(22), files[f].join('x').padEnd(10), kb.toFixed(0) + ' KB');
}
console.log('total'.padEnd(33), total.toFixed(0) + ' KB');
